services:
  readme.users.mongo:
    image: mongo:4.4
    restart: always
    container_name: readme.users.mongo

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_NAME}

    ports:
      - 27017:27017

    volumes:
      - readme.mongo.users:/data/db

    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@$localhost:27017/?authSource=${MONGO_NAME} --quiet
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  readme.mongo.users:
